<?php
// languages/common.php

return [
    'es' => [
        // General
        'zapp_citas' => 'ZApp Citas',
        'welcome' => 'Bienvenido',
        'dashboard' => 'Dashboard',
        'go_back' => 'Volver',
        'save' => 'Guardar',
        'edit' => 'Editar',
        'delete' => 'Eliminar',
        'deactivate' => 'Desactivar',
        'actions' => 'Acciones',
        'status' => 'Estado',
        'active' => 'Activo',
        'inactive' => 'Inactivo',
        'cancel' => 'Cancelar',
        'operation_success' => 'Operación realizada con éxito.',
        'operation_error' => 'Ocurrió un error.',
        'error_invalid_id' => 'ID no válido.',
        'error_not_found' => 'Registro no encontrado.',
        'error_duplicate_entry' => 'La entrada ya existe.',
        'error_in_use' => 'No se puede eliminar, el registro está en uso.',
        'error_all_fields_required' => 'Todos los campos son obligatorios.',
        'error_invalid_email' => 'El formato del correo electrónico no es válido.',
        'create_success' => 'Registro creado con éxito.',
        'update_success' => 'Registro actualizado con éxito.',
        'deactivate_success' => 'Registro desactivado con éxito.',
        'delete_success' => 'Registro eliminado con éxito.',
        'are_you_sure' => '¿Estás seguro?',

        // Días de la semana
        'day_1' => 'Lunes', 
        'day_2' => 'Martes', 
        'day_3' => 'Miércoles', 
        'day_4' => 'Jueves', 
        'day_5' => 'Viernes', 
        'day_6' => 'Sábado', 
        'day_7' => 'Domingo',

        // Email Content
        'email_hello' => '¡Hola {name}!',
        'email_regards' => 'Atentamente,',
        'email_team' => 'El equipo de ZApp Citas',
        'email_service' => 'Servicio',
        'email_meeting_subject' => 'Tema',
        'email_date' => 'Fecha',
        'email_time' => 'Hora',
        'email_client_data' => 'Datos del Cliente',
        'email_name' => 'Nombre',
        'email_email' => 'Correo',
        'email_phone' => 'Teléfono',
        'email_not_specified' => 'No especificado',
    ],
    'en' => [
        // General
        'zapp_citas' => 'ZApp Citas',
        'welcome' => 'Welcome',
        'dashboard' => 'Dashboard',
        'go_back' => 'Go Back',
        'save' => 'Save',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'deactivate' => 'Deactivate',
        'actions' => 'Actions',
        'status' => 'Status',
        'active' => 'Active',
        'inactive' => 'Inactive',
        'cancel' => 'Cancel',
        'operation_success' => 'Operation completed successfully.',
        'operation_error' => 'An error occurred.',
        'error_invalid_id' => 'Invalid ID.',
        'error_not_found' => 'Record not found.',
        'error_duplicate_entry' => 'The entry already exists.',
        'error_in_use' => 'Cannot delete, the record is in use.',
        'error_all_fields_required' => 'All fields are required.',
        'error_invalid_email' => 'The email format is invalid.',
        'create_success' => 'Record created successfully.',
        'update_success' => 'Record updated successfully.',
        'deactivate_success' => 'Record deactivated successfully.',
        'delete_success' => 'Record deleted successfully.',
        'are_you_sure' => 'Are you sure?',

        // Días de la semana
        'day_1' => 'Monday', 'day_2' => 'Tuesday', 'day_3' => 'Wednesday', 'day_4' => 'Thursday', 'day_5' => 'Friday', 'day_6' => 'Saturday', 'day_7' => 'Sunday',

        // Email Content
        'email_hello' => 'Hello {name}!',
        'email_regards' => 'Regards,',
        'email_team' => 'The ZApp Citas Team',
        'email_service' => 'Service',
        'email_meeting_subject' => 'Subject',
        'email_date' => 'Date',
        'email_time' => 'Time',
        'email_client_data' => 'Client Details',
        'email_name' => 'Name',
        'email_email' => 'Email',
        'email_phone' => 'Phone',
        'email_not_specified' => 'Not specified',
    ]
];