<?php
// languages/help.php

return [
    'es' => [
        // General Help
        'help_close_window' => 'Cerrar Ventana',

        // Ayuda Index
        'help_index_title' => 'Ayuda - Página Principal de ZApp Citas',
        'help_index_header' => 'Ayuda: Página Principal',
        'help_index_objective_title' => 'Objetivo de la Pantalla Principal',
        'help_index_objective_body' => 'La pantalla principal de <strong>ZApp Citas</strong> es el portal de acceso a las diferentes interfaces de la aplicación. Desde aquí, los usuarios pueden navegar a la sección que les corresponde según su rol.',
        'help_index_admin_title' => 'ZApp Citas (Administración)',
        'help_index_admin_desc' => 'Esta sección es el panel de control central para los administradores del sistema.',
        'help_index_admin_func_1' => 'Gestión completa de todos los negocios registrados.',
        'help_index_admin_func_2' => 'Creación y administración de usuarios (Propietarios).',
        'help_index_admin_func_3' => 'Configuración de parámetros globales como países, categorías, etc.',
        'help_index_admin_func_4' => 'Auditoría y supervisión de toda la plataforma.',
        'help_index_admin_access' => 'Requiere un usuario y contraseña de administrador.',
        'help_index_client_title' => 'App Cliente',
        'help_index_client_desc' => 'Interfaz diseñada para que los clientes finales puedan gestionar sus propias citas de forma autónoma.',
        'help_index_client_func_1' => 'Agendar nuevas citas seleccionando un negocio, servicio y horario disponible.',
        'help_index_client_func_2' => 'Ver el historial de sus citas pasadas y futuras.',
        'help_index_client_func_3' => 'Confirmar o cancelar una cita pendiente.',
        'help_index_client_func_4' => 'Actualizar sus datos de perfil.',
        'help_index_client_access' => 'Se realiza mediante su número de teléfono celular y un código de seguridad (CAPTCHA).',
        'help_functionalities' => 'Funcionalidades:',
        'help_access' => 'Acceso:',

        // Ayuda ZApp Citas (Admin)
        'help_admin_title' => 'Ayuda - Panel de Administración ZApp Citas',
        'help_admin_header' => 'Ayuda: Panel de Administración',
        'help_admin_objective_title' => 'Objetivo del Panel de Administración',
        'help_admin_objective_body' => 'El Panel de Administración (<strong>ZApp Citas</strong>) es el centro de control para los administradores del sistema. Permite gestionar todos los aspectos de la plataforma, desde la configuración de negocios y servicios hasta la supervisión de usuarios y citas.',
        'help_admin_dash_desc' => 'Es la pantalla de bienvenida. Ofrece accesos directos a las funciones más comunes y muestra información relevante del negocio seleccionado.',
        'help_admin_dash_func_1' => 'Accesos rápidos para Agendar Cita, Ver Calendario y Gestionar Clientes.',
        'help_admin_dash_func_2' => 'Muestra el nombre del negocio actual y un reloj en tiempo real.',
        'help_admin_biz_desc' => 'Permite crear, editar y configurar todos los negocios de la plataforma.',
        'help_admin_biz_func_1' => 'Crear nuevos negocios y asignarles un usuario "Propietario".',
        'help_admin_biz_func_2' => 'Editar datos de contacto, dirección y categoría de un negocio.',
        'help_admin_biz_func_3' => 'Definir el horario de trabajo (días, hora de inicio/cierre e intervalo entre citas).',
        'help_admin_biz_func_4' => 'Gestionar el período de prueba y subir una imagen de fondo personalizada.',
        'help_admin_clients_services_desc' => 'Secciones para administrar la base de clientes y el catálogo de servicios de cada negocio.',
        'help_admin_clients_title' => 'Clientes:',
        'help_admin_clients_func_1' => 'Registrar nuevos clientes con sus datos de contacto y dirección.',
        'help_admin_clients_func_2' => 'Editar la información de clientes existentes.',
        'help_admin_clients_func_3' => 'Desactivar clientes (borrado lógico) para que no puedan agendar nuevas citas.',
        'help_admin_services_title' => 'Servicios:',
        'help_admin_services_func_1' => 'Crear nuevos servicios definiendo su nombre, duración y precio.',
        'help_admin_services_func_2' => 'Editar o desactivar servicios existentes.',
        'help_admin_appoint_desc' => 'El corazón de la aplicación. Permite gestionar todo el ciclo de vida de las citas.',
        'help_admin_appoint_func_1' => 'Agendar nuevas citas de tipo "Servicio" o "Reunión".',
        'help_admin_appoint_func_2' => 'Para reuniones, se pueden añadir múltiples invitados con su correo.',
        'help_admin_appoint_func_3' => 'Ver la lista de citas de un día específico y filtrar por fecha.',
        'help_admin_appoint_func_4' => 'Cambiar el estado de una cita (Confirmar, Completar, Cancelar, etc.).',
        'help_admin_appoint_func_5' => 'El <strong>Calendario</strong> ofrece una vista mensual de todas las citas agendadas.',
        'help_admin_appoint_func_6' => 'La opción <strong>Cierre Citas</strong> permite marcar como "Vencidas" todas las citas pasadas que quedaron pendientes.',

        // Ayuda SPA Owner
        'help_owner_title' => 'Ayuda - App del Propietario',
        'help_owner_header' => 'Ayuda: App del Propietario',
        'help_owner_objective_title' => 'Objetivo de la App del Propietario',
        'help_owner_objective_body' => 'Esta aplicación está diseñada para que el dueño o encargado del negocio pueda gestionar la operativa diaria de sus citas, clientes y servicios de forma rápida y sencilla desde cualquier dispositivo.',
        'help_owner_agenda_desc' => 'Es la vista principal. Muestra la lista de citas para un día específico.',
        'help_owner_agenda_func_1' => 'Navegar entre días para ver las citas pasadas o futuras.',
        'help_owner_agenda_func_2' => 'Crear nuevas citas de tipo "Servicio" o "Reunión".',
        'help_owner_agenda_func_3' => 'Editar una cita existente para cambiar su estado, fecha, hora o añadir notas.',
        'help_owner_calendar_desc' => 'Ofrece una vista de calendario mensual o semanal, permitiendo ver la ocupación de un vistazo y acceder rápidamente a los detalles de una cita.',
        'help_owner_clients_services_desc' => 'Secciones dedicadas a la gestión de la base de datos de clientes y el catálogo de servicios del negocio.',
        'help_owner_clients_func_1' => 'Registrar nuevos clientes o editar la información de los existentes.',
        'help_owner_clients_func_2' => 'Activar o desactivar clientes.',
        'help_owner_services_func_1' => 'Crear, editar o desactivar los servicios que ofrece el negocio.',
        'help_owner_services_func_2' => 'Definir nombre, duración y precio de cada servicio.',
        'help_owner_business_profile_desc' => '<strong>Mi Negocio:</strong> Permite ajustar la configuración básica del negocio, como el horario de atención. <strong>Mi Perfil:</strong> Permite al usuario cambiar su propia contraseña de acceso.',
    ],
    'en' => [
        // General Help
        'help_close_window' => 'Close Window',

        // Ayuda Index
        'help_index_title' => 'Help - ZApp Citas Main Page',
        'help_index_header' => 'Help: Main Page',
        'help_index_objective_title' => 'Objective of the Main Screen',
        'help_index_objective_body' => 'The main screen of <strong>ZApp Citas</strong> is the access portal to the different interfaces of the application. From here, users can navigate to the section that corresponds to their role.',
        'help_index_admin_title' => 'ZApp Citas (Administration)',
        'help_index_admin_desc' => 'This section is the central control panel for system administrators.',
        'help_index_admin_func_1' => 'Complete management of all registered businesses.',
        'help_index_admin_func_2' => 'Creation and administration of users (Owners).',
        'help_index_admin_func_3' => 'Configuration of global parameters such as countries, categories, etc.',
        'help_index_admin_func_4' => 'Auditing and supervision of the entire platform.',
        'help_index_admin_access' => 'Requires an administrator username and password.',
        'help_index_client_title' => 'Client App',
        'help_index_client_desc' => 'Interface designed for end customers to manage their own appointments autonomously.',
        'help_index_client_func_1' => 'Schedule new appointments by selecting a business, service, and available time.',
        'help_index_client_func_2' => 'View the history of their past and future appointments.',
        'help_index_client_func_3' => 'Confirm or cancel a pending appointment.',
        'help_index_client_func_4' => 'Update their profile data.',
        'help_index_client_access' => 'Access is via their mobile phone number and a security code (CAPTCHA).',
        'help_functionalities' => 'Functionalities:',
        'help_access' => 'Access:',

        // Ayuda ZApp Citas (Admin)
        'help_admin_title' => 'Help - ZApp Citas Admin Panel',
        'help_admin_header' => 'Help: Admin Panel',
        'help_admin_objective_title' => 'Objective of the Admin Panel',
        'help_admin_objective_body' => 'The Admin Panel (<strong>ZApp Citas</strong>) is the control center for system administrators. It allows managing all aspects of the platform, from business and service configuration to user and appointment supervision.',
        'help_admin_dash_desc' => 'This is the welcome screen. It offers shortcuts to the most common functions and displays relevant information for the selected business.',
        'help_admin_dash_func_1' => 'Quick access to Schedule Appointment, View Calendar, and Manage Clients.',
        'help_admin_dash_func_2' => 'Displays the current business name and a real-time clock.',
        'help_admin_biz_desc' => 'Allows creating, editing, and configuring all businesses on the platform.',
        'help_admin_biz_func_1' => 'Create new businesses and assign them an "Owner" user.',
        'help_admin_biz_func_2' => 'Edit contact details, address, and category of a business.',
        'help_admin_biz_func_3' => 'Define the work schedule (days, start/end time, and interval between appointments).',
        'help_admin_biz_func_4' => 'Manage the trial period and upload a custom background image.',
        'help_admin_clients_services_desc' => 'Sections to manage the client base and the service catalog of each business.',
        'help_admin_clients_title' => 'Clients:',
        'help_admin_clients_func_1' => 'Register new clients with their contact and address details.',
        'help_admin_clients_func_2' => 'Edit the information of existing clients.',
        'help_admin_clients_func_3' => 'Deactivate clients (soft delete) so they cannot schedule new appointments.',
        'help_admin_services_title' => 'Services:',
        'help_admin_services_func_1' => 'Create new services by defining their name, duration, and price.',
        'help_admin_services_func_2' => 'Edit or deactivate existing services.',
        'help_admin_appoint_desc' => 'The heart of the application. It allows managing the entire lifecycle of appointments.',
        'help_admin_appoint_func_1' => 'Schedule new "Service" or "Meeting" type appointments.',
        'help_admin_appoint_func_2' => 'For meetings, multiple guests with their email can be added.',
        'help_admin_appoint_func_3' => 'View the list of appointments for a specific day and filter by date.',
        'help_admin_appoint_func_4' => 'Change the status of an appointment (Confirm, Complete, Cancel, etc.).',
        'help_admin_appoint_func_5' => 'The <strong>Calendar</strong> offers a monthly view of all scheduled appointments.',
        'help_admin_appoint_func_6' => 'The <strong>Close Appointments</strong> option allows marking all past pending appointments as "Overdue".',

        // Ayuda SPA Owner
        'help_owner_title' => 'Help - Owner App',
        'help_owner_header' => 'Help: Owner App',
        'help_owner_objective_title' => 'Objective of the Owner App',
        'help_owner_objective_body' => 'This application is designed for the business owner or manager to handle the daily operations of their appointments, clients, and services quickly and easily from any device.',
        'help_owner_agenda_desc' => 'This is the main view. It shows the list of appointments for a specific day.',
        'help_owner_agenda_func_1' => 'Navigate between days to see past or future appointments.',
        'help_owner_agenda_func_2' => 'Create new "Service" or "Meeting" type appointments.',
        'help_owner_agenda_func_3' => 'Edit an existing appointment to change its status, date, time, or add notes.',
        'help_owner_calendar_desc' => 'Provides a monthly or weekly calendar view, allowing you to see occupancy at a glance and quickly access appointment details.',
        'help_owner_clients_services_desc' => 'Sections dedicated to managing the client database and the business\'s service catalog.',
        'help_owner_clients_func_1' => 'Register new clients or edit the information of existing ones.',
        'help_owner_clients_func_2' => 'Activate or deactivate clients.',
        'help_owner_services_func_1' => 'Create, edit, or deactivate the services offered by the business.',
        'help_owner_services_func_2' => 'Define the name, duration, and price of each service.',
        'help_owner_business_profile_desc' => '<strong>My Business:</strong> Allows adjusting basic business settings, such as opening hours. <strong>My Profile:</strong> Allows the user to change their own login password.',
    ]
];