<?php
// Elaborado por GEMINI ASSIST y Alexis Gutierrez de www.ACTICVEN.COM
// ©2025. Software development ad Autorized by WWW.ACTICVEN.COM All rights reserved.
// Update: Dec-05-2025. Sistema central de internacionalización (i18n).

// NOTA: session_start() se elimina de aquí.
// El script que incluya este archivo (ej. auth_check.php o sesion_iniciar.php)
// es responsable de iniciar la sesión ANTES de incluirlo.

// 1. Determinar el idioma
// Prioridad: 1. Parámetro en URL (?lang=en), 2. Cookie, 3. Sesión, 4. Por defecto 'es'
$lang = 'es'; // Idioma por defecto
if (isset($_GET['lang']) && in_array($_GET['lang'], ['es', 'en'])) {
    $lang = $_GET['lang'];
    $_SESSION['lang'] = $lang;
    setcookie('lang', $lang, time() + (3600 * 24 * 30), "/"); // Guardar por 30 días
} elseif (isset($_SESSION['lang'])) {
    $lang = $_SESSION['lang'];
} elseif (isset($_COOKIE['lang'])) {
    $lang = $_COOKIE['lang'];
}

// 2. Array central de traducciones
$translations = [
    'es' => [
        // General
        'zapp_citas' => 'ZApp Citas',
        'welcome' => 'Bienvenido',
        'dashboard' => 'Dashboard',
        'go_back' => 'Volver',
        'save' => 'Guardar',
        'edit' => 'Editar',
        'delete' => 'Eliminar',
        'deactivate' => 'Desactivar',
        'actions' => 'Acciones',
        'status' => 'Estado',
        'active' => 'Activo',
        'inactive' => 'Inactivo',
        'cancel' => 'Cancelar',
        'operation_success' => 'Operación realizada con éxito.',
        'operation_error' => 'Ocurrió un error.',
        'error_invalid_id' => 'ID no válido.',
        'error_not_found' => 'Registro no encontrado.',
        'error_duplicate_entry' => 'La entrada ya existe.',
        'error_in_use' => 'No se puede eliminar, el registro está en uso.',
        'error_all_fields_required' => 'Todos los campos son obligatorios.',
        'error_invalid_email' => 'El formato del correo electrónico no es válido.',
        'create_success' => 'Registro creado con éxito.',
        'update_success' => 'Registro actualizado con éxito.',
        'delete_success' => 'Registro eliminado con éxito.',

        // Navbar
        'businesses' => 'Negocios',
        'services' => 'Servicios',
        'clients' => 'Clientes',
        'appointments' => 'Citas',
        'calendar' => 'Calendario',
        'close_appointments' => 'Cierre Citas',
        'users' => 'Usuarios',
        'categories' => 'Categorías',
        'locations' => 'Localizaciones',
        'audit' => 'Auditoría',
        'documents' => 'Documentos',
        'configuration' => 'Configuración',
        'my_profile' => 'Mi Perfil',
        'logout' => 'Salir',

        // Login Page (sesion_iniciar.php)
        'login_title' => 'Iniciar Sesión',
        'login_user' => 'Usuario',
        'login_password' => 'Contraseña',
        'login_button' => 'Entrar',
        'login_forgot_password' => 'Olvidé mi clave de usuario',
        'login_error_inactive' => 'Tu cuenta de usuario ha sido desactivada.',
        'login_error_password' => 'Contraseña incorrecta.',
        'login_error_not_found' => 'Usuario no encontrado.',
        'login_error_session_expired' => 'Tu sesión ha expirado por inactividad. Por favor, inicia sesión de nuevo.',
        'login_back_to_home' => 'Volver al inicio',

        // Dashboard
        'dashboard_welcome_to' => 'Bienvenido a',
        'dashboard_subtitle' => 'Su asistente personal para la gestión de citas.',
        'dashboard_card_schedule' => 'Agendar Cita',
        'dashboard_card_calendar' => 'Ver Calendario',
        'dashboard_card_clients' => 'Gestionar Clientes',

        // Clients Page (clientes_lista.php)
        'clients_title' => 'Gestión de Clientes',
        'clients_register_new' => 'Registrar Nuevo Cliente',
        'clients_form_name' => 'Nombre Completo',
        'clients_form_phone' => 'Número de Celular',
        'clients_form_email' => 'Correo Electrónico',
        'clients_form_save' => 'Guardar Cliente',
        'clients_list_title' => 'Lista de Clientes',
        'clients_list_for' => 'Para',
        'clients_col_name' => 'Nombre',
        'clients_col_phone' => 'Celular',
        'clients_col_email' => 'Email',
        'clients_col_status' => 'Estado',
        'clients_form_address1' => 'Dirección 1',
        'clients_form_address2' => 'Dirección 2 (Opcional)',
        'clients_form_country' => 'País',
        'clients_form_state' => 'Estado / Provincia',
        'clients_form_city' => 'Ciudad',
        'clients_form_zip' => 'Código Postal',
        'clients_form_notes' => 'Notas Adicionales',
        'clients_form_communication' => 'Preferencias de Comunicación:',
        'clients_form_sms_notifications' => 'Recibir notificaciones por SMS',
        'clients_form_email_notifications' => 'Recibir notificaciones por Email',
        'clients_form_clear' => 'Limpiar Formulario',
        'clients_no_clients' => 'No hay clientes registrados todavía.',
        'clients_confirm_deactivate' => '¿Estás seguro de que quieres desactivar este cliente? No se podrá usar para nuevas citas, pero su historial se conservará.',
        'clients_edit_title' => 'Editar Cliente',
        'clients_editing' => 'Editando a',
        'clients_form_active' => 'Cliente Activo',
        'clients_form_update' => 'Actualizar Cliente',

        // Businesses Page (negocios_configuracion.php)
        'businesses_title' => 'Configuración del Negocio',
        'businesses_manage_title' => 'Gestión de Negocios',
        'businesses_select_or_create' => 'Seleccione un negocio para editar o cree uno nuevo.',
        'businesses_status_suspended' => 'Suspendido',
        'businesses_status_deleted' => 'Eliminado',
        'businesses_create_new' => 'Crear Nuevo Negocio',
        'businesses_config_for' => 'Configuración de',
        'businesses_form_id' => 'ID de Negocio',
        'businesses_form_name' => 'Nombre del Negocio',
        'businesses_form_phone' => 'Teléfono',
        'businesses_form_phone_local' => 'Número local',
        'businesses_form_email' => 'Email de Contacto',
        'businesses_form_category' => 'Categoría del Negocio',
        'businesses_form_no_category' => '-- Sin Categoría --',
        'businesses_form_status' => 'Estado del Negocio',
        'businesses_form_address1' => 'Dirección 1',
        'businesses_form_address2' => 'Dirección 2 (Opcional)',
        'businesses_form_country' => 'País',
        'businesses_form_select_country' => 'Seleccione un país...',
        'businesses_form_state' => 'Estado / Provincia',
        'businesses_form_loading' => 'Cargando...',
        'businesses_form_city' => 'Ciudad',
        'businesses_form_zip' => 'Código Postal',
        'businesses_schedule_title' => 'Horario de Trabajo',
        'businesses_schedule_days' => 'Días de Trabajo',
        'day_1' => 'Lunes', 'day_2' => 'Martes', 'day_3' => 'Miércoles', 'day_4' => 'Jueves', 'day_5' => 'Viernes', 'day_6' => 'Sábado', 'day_7' => 'Domingo',
        'businesses_schedule_start' => 'Hora de Inicio',
        'businesses_schedule_end' => 'Hora de Cierre',
        'businesses_schedule_interval' => 'Intervalo (minutos)',
        'businesses_trial_title' => 'Gestión del Período de Prueba',
        'businesses_trial_reg_date' => 'Fecha de Registro',
        'businesses_trial_start_date' => 'Fecha de Habilitación (Inicio Prueba)',
        'businesses_trial_days' => 'Días de Prueba Asignados',
        'businesses_trial_end_date' => 'Fecha de Desactivación (Manual)',
        'businesses_trial_note' => 'Ajusta los días o la fecha final. La fecha final tiene prioridad.',
        'businesses_bg_image_title' => 'Imagen de Fondo',
        'businesses_bg_image_upload' => 'Subir nueva imagen de fondo (opcional)',
        'businesses_bg_image_current' => 'Imagen Actual:',
        'businesses_form_save' => 'Guardar Configuración',
        'businesses_create_title' => 'Crear Nuevo Negocio',
        'businesses_create_instructions' => 'Complete los datos básicos. Podrá añadir más detalles (horarios, imagen, etc.) después de crearlo.',
        'businesses_create_owner_title' => 'Crear Usuario Propietario',
        'businesses_create_owner_instructions' => 'Se creará un usuario \'Propietario\' para este nuevo negocio.',
        'businesses_create_owner_user' => 'Nombre de Usuario Propietario',
        'businesses_create_owner_password' => 'Contraseña para Propietario',
        'businesses_create_owner_email' => 'Email del Usuario Propietario',
        'businesses_create_button' => 'Crear Negocio y Usuario Propietario',

        // Services Page (servicios_lista.php & servicios_editar.php)
        'services_title' => 'Gestión de Servicios',
        'services_register_new' => 'Registrar Nuevo Servicio',
        'services_form_name' => 'Nombre del Servicio',
        'services_form_duration' => 'Duración',
        'duration_minutes' => 'Minutos',
        'duration_hours' => 'Horas',
        'duration_days' => 'Días',
        'services_form_price' => 'Precio (opcional)',
        'services_form_save' => 'Guardar Servicio',
        'services_form_clear' => 'Limpiar Formulario',
        'services_list_title' => 'Lista de Servicios',
        'services_col_service' => 'Servicio',
        'services_col_duration' => 'Duración',
        'services_col_price' => 'Precio',
        'services_confirm_deactivate' => '¿Estás seguro de que quieres desactivar este servicio?',
        'services_no_services' => 'No hay servicios registrados.',
        'services_edit_title' => 'Editar Servicio',
        'services_editing' => 'Editando Servicio',
        'services_form_active' => 'Servicio Activo',
        'services_form_update' => 'Actualizar Servicio',

        // Appointments Page (citas_lista.php & citas_editar.php)
        'appointments_title' => 'Gestión de Citas',
        'appointments_schedule_new' => 'Agendar Nueva Cita',
        'appointments_type' => 'Tipo de Cita',
        'appointments_type_service' => 'Cita de Servicio',
        'appointments_type_meeting' => 'Reunión',
        'appointments_client' => 'Cliente',
        'appointments_select_client' => 'Seleccione un cliente...',
        'appointments_service' => 'Servicio',
        'appointments_select_service' => 'Seleccione un servicio...',
        'appointments_date' => 'Fecha de la Cita',
        'appointments_time' => 'Hora de la Cita',
        'appointments_select_time' => 'Seleccione una hora...',
        'appointments_additional_desc' => 'Descripción Adicional',
        'appointments_meeting_subject' => 'Tema de la Reunión',
        'appointments_meeting_guests' => 'Invitados a la Reunión',
        'appointments_add_guest' => '+ Añadir Invitado',
        'appointments_schedule_button' => 'Agendar Cita',
        'appointments_list_title' => 'Lista de Citas',
        'appointments_filter_day' => 'Día:',
        'appointments_filter_button' => 'Filtrar',
        'appointments_prev_day' => '⬅️ Anterior',
        'appointments_next_day' => 'Siguiente ➡️',
        'appointments_col_schedule' => 'Horario',
        'appointments_col_duration' => 'Duración',
        'appointments_no_appointments_for_day' => 'No hay citas agendadas para el día',
        'appointments_edit_title' => 'Editar Cita',
        'appointments_editing_title' => 'Editando Cita',

        // Calendar Page (calendario_ver.php)
        'calendar_title' => 'Calendario de Citas',

        // Close Appointments Page (citas_cerrar_vencidas.php)
        'close_appointments_title' => 'Cierre de Citas Vencidas',
        'close_appointments_header' => 'Cierre Manual de Citas Vencidas',
        'close_appointments_desc_1' => "Esta herramienta buscará todas las citas con estado 'Pendiente' cuya fecha y hora ya hayan pasado y las actualizará automáticamente al estado 'Vencida'.",
        'close_appointments_desc_2' => 'Esto ayuda a mantener su agenda limpia y sus reportes actualizados.',
        'close_appointments_button' => 'Iniciar Proceso de Cierre',
        'close_appointments_success' => 'Proceso completado. Se han actualizado {count} citas al estado \'Vencida\'.',

        // Users Page (usuarios_lista.php & usuarios_editar.php)
        'users_title' => 'Gestión de Usuarios',
        'users_register_new' => 'Registrar Nuevo Usuario',
        'users_form_username' => 'Nombre de Usuario',
        'users_form_email' => 'Correo Electrónico',
        'users_form_password' => 'Contraseña',
        'users_form_role' => 'Rol',
        'users_role_owner' => 'Propietario',
        'users_form_business' => 'Negocio Asignado',
        'users_form_active' => 'Usuario Activo',
        'users_form_save' => 'Guardar Usuario',
        'users_list_title' => 'Lista de Usuarios',
        'users_col_user' => 'Usuario',
        'users_col_business' => 'Negocio',
        'users_confirm_delete' => '¿Estás seguro de que quieres eliminar este usuario?',
        'users_not_allowed' => '(No permitido)',
        'users_no_users' => 'No hay usuarios registrados.',
        'users_edit_title' => 'Editar Usuario',
        'users_editing' => 'Editando a',
        'users_form_new_password' => 'Nueva Contraseña',
        'users_form_new_password_placeholder' => 'Dejar en blanco para no cambiar',
        'users_form_update' => 'Actualizar Usuario',

        // Categories Page (categorias_lista.php, etc.)
        'categories_title' => 'Gestión de Categorías',
        'categories_create_new' => 'Crear Nueva Categoría',
        'categories_list_title' => 'Gestión de Categorías de Negocio',
        'categories_col_name' => 'Nombre de Categoría',
        'categories_col_desc' => 'Descripción',
        'categories_confirm_delete' => '¿Estás seguro de que quieres eliminar esta categoría? Podría estar en uso por algún negocio.',
        'categories_edit_title' => 'Editar Categoría',
        'categories_editing' => 'Editando Categoría',
        'categories_form_active' => 'Categoría Activa',
        'categories_form_update' => 'Actualizar Categoría',

        // Locations Page (paises_lista.php, estados_lista.php, etc.)
        'locations_countries_title' => 'Gestión de Países',
        'locations_register_country' => 'Registrar Nuevo País',
        'locations_form_country_name' => 'Nombre del País',
        'locations_form_country_code' => 'Código (2 letras, ej: US)',
        'locations_form_phone_code' => 'Código Telefónico (ej: +1)',
        'locations_form_timezone' => 'Zona Horaria Principal',
        'locations_form_select_timezone' => 'Seleccione...',
        'locations_form_save_country' => 'Guardar País',
        'locations_list_countries' => 'Lista de Países',
        'locations_col_country' => 'País',
        'locations_col_code' => 'Código',
        'locations_col_phone' => 'Tel.',
        'locations_col_timezone' => 'Zona Horaria',
        'locations_action_states' => 'Estados',
        'locations_confirm_delete_country' => '¿Seguro que quieres eliminar este país y TODOS sus estados asociados?',
        'locations_no_countries' => 'No hay países registrados.',
        'locations_edit_country_title' => 'Editar País',
        'locations_editing_country' => 'Editando País',
        'locations_update_country' => 'Actualizar País',
        'locations_states_title' => 'Gestión de Estados para {country}',
        'locations_back_to_countries' => '← Volver a Países',
        'locations_register_state' => 'Registrar Nuevo Estado',
        'locations_form_state_name' => 'Nombre del Estado / Provincia',
        'locations_form_save_state' => 'Guardar Estado',
        'locations_list_states' => 'Lista de Estados',
        'locations_confirm_delete_state' => '¿Estás seguro?',
        'locations_no_states' => 'No hay estados registrados para este país.',
        'locations_edit_state_title' => 'Editar Estado',
        'locations_editing_state' => 'Editando Estado',
        'locations_update_state' => 'Actualizar Estado',

        // Audit Page (auditoria_reporte.php)
        'audit_title' => 'Reporte de Auditoría',
        'audit_filter_title' => 'Filtrar Registros',
        'audit_filter_from' => 'Desde',
        'audit_filter_to' => 'Hasta',
        'audit_filter_all' => 'Todos',
        'audit_filter_clear' => 'Limpiar',
        'audit_report_title' => 'Reporte de Auditoría (Audit Trail)',
        'audit_showing_records' => 'Mostrando {count} de {total} Registros',
        'audit_col_datetime' => 'Fecha y Hora',
        'audit_col_ip' => 'Dirección IP',
        'audit_user_system' => 'Sistema/Eliminado',
        'audit_business_na' => 'N/A',
        'audit_no_records' => 'No hay registros de auditoría que coincidan con los filtros.',

        // Documents Page (seleccionar_resumen.php, etc.)
        'documents_title' => 'Documentos',
        'documents_select_or_upload' => 'Selecciona un documento para ver, editar o enviar, o sube uno nuevo.',
        'documents_no_files' => 'No se encontraron documentos en el directorio.',
        'documents_view' => 'Ver',
        'documents_send' => 'Enviar',
        'documents_confirm_send' => '¿Estás seguro de que quieres enviar este documento por correo?',
        'documents_confirm_delete' => '¿Estás seguro de que quieres eliminar este documento de forma permanente?',
        'documents_upload_title' => 'Subir Nuevo Documento',
        'documents_upload_select' => 'Seleccionar archivo (.txt, .pdf, .md)',
        'documents_upload_button' => 'Subir Documento',
        'documents_edit_md_title' => 'Editar Documento Markdown',
        'documents_editing' => 'Editando',
        'documents_edit_txt_title' => 'Editar Documento',
        'documents_edit_txt_note' => 'Nota: Las cabeceras (FROM, TO, SUBJECT) no son editables desde aquí.',
        'documents_send_pdf_title' => 'Enviar Documento PDF',
        'documents_send_pdf_about_to_send' => 'Estás a punto de enviar el siguiente documento como archivo adjunto:',
        'documents_send_pdf_file' => 'Archivo',
        'documents_send_pdf_to' => 'Correo del Destinatario (TO):',
        'documents_send_pdf_subject' => 'Asunto del Correo:',
        'documents_send_pdf_button' => 'Enviar Correo con Adjunto',
        'documents_viewer_title' => 'Visor',

        // Email Content
        'email_hello' => '¡Hola {name}!',
        'email_regards' => 'Atentamente,',
        'email_team' => 'El equipo de ZApp Citas',
        'email_service' => 'Servicio',
        'email_meeting_subject' => 'Tema',
        'email_date' => 'Fecha',
        'email_time' => 'Hora',
        'email_client_data' => 'Datos del Cliente',
        'email_name' => 'Nombre',
        'email_email' => 'Correo',
        'email_phone' => 'Teléfono',
        'email_not_specified' => 'No especificado',

        // New Appointment
        'email_new_subject_service' => 'Confirmación de tu cita en {business_name}',
        'email_new_subject_meeting' => 'Invitación a Reunión: {event_title}',
        'email_new_title_service' => '¡Tu cita ha sido agendada con éxito!',
        'email_new_title_meeting' => '¡Has sido invitado a una reunión!',
        'email_new_body' => 'Aquí están los detalles:',
        'email_new_footer' => '<strong>Importante:</strong> Por favor, asiste 5 minutos antes de la hora acordada para respetar el tiempo de agenda de otros clientes.',

        // Modified Appointment
        'email_modified_subject_service' => 'Actualización de tu cita en {business_name}',
        'email_modified_subject_meeting' => 'Actualización de Reunión: {event_title}',
        'email_modified_title_service' => '¡Tu cita ha sido modificada!',
        'email_modified_title_meeting' => 'La reunión ha sido modificada',
        'email_modified_body' => 'Estos son los nuevos detalles:',
        'email_modified_footer' => 'Por favor, revisa los nuevos detalles y contáctanos si tienes alguna pregunta.',

        // Cancelled Appointment
        'email_cancelled_subject_service' => 'Cancelación de tu cita en {business_name}',
        'email_cancelled_subject_meeting' => 'Cancelación de Reunión: {event_title}',
        'email_cancelled_title_service' => 'Tu cita ha sido cancelada.',
        'email_cancelled_title_meeting' => 'La reunión ha sido cancelada',
        'email_cancelled_body' => 'Lamentamos informarte que el siguiente evento ha sido cancelado:',
        'email_cancelled_footer' => 'Si deseas reagendar, no dudes en ponerte en contacto con nosotros.',

        // Password Recovery
        'email_recovery_subject' => 'Recuperación de Contraseña - ZApp Citas',
        'email_recovery_title' => 'Recuperación de Contraseña',
        'email_recovery_body' => 'Has solicitado restablecer tu contraseña. Aquí están tus nuevos datos de acceso:',
        'email_recovery_user' => 'Usuario',
        'email_recovery_password' => 'Nueva Contraseña Temporal',
        'email_recovery_footer' => 'Te recomendamos iniciar sesión y cambiar esta contraseña por una de tu elección lo antes posible.',
        'email_recovery_ignore' => 'Si no solicitaste esto, puedes ignorar este correo.',
        'email_recovery_generic_success' => 'Si tu correo está en nuestro sistema, recibirás un email con instrucciones.',

        // Forgot Password Page
        'forgot_password_title' => 'Recuperar Contraseña',
        'forgot_password_instructions' => 'Ingresa tu correo electrónico y te enviaremos una nueva contraseña temporal si la cuenta existe.',
        'forgot_password_button' => 'Enviar Instrucciones',
        'forgot_password_back_to_login' => 'Volver al Login',
    ],
    'en' => [
        // General
        'zapp_citas' => 'ZApp Citas',
        'welcome' => 'Welcome',
        'dashboard' => 'Dashboard',
        'go_back' => 'Go Back',
        'save' => 'Save',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'deactivate' => 'Deactivate',
        'actions' => 'Actions',
        'status' => 'Status',
        'active' => 'Active',
        'inactive' => 'Inactive',
        'cancel' => 'Cancel',
        'operation_success' => 'Operation completed successfully.',
        'operation_error' => 'An error occurred.',
        'error_invalid_id' => 'Invalid ID.',
        'error_not_found' => 'Record not found.',
        'error_duplicate_entry' => 'The entry already exists.',
        'error_in_use' => 'Cannot delete, the record is in use.',
        'error_all_fields_required' => 'All fields are required.',
        'error_invalid_email' => 'The email format is invalid.',
        'create_success' => 'Record created successfully.',
        'update_success' => 'Record updated successfully.',
        'delete_success' => 'Record deleted successfully.',

        // Navbar
        'businesses' => 'Businesses',
        'services' => 'Services',
        'clients' => 'Clients',
        'appointments' => 'Appointments',
        'calendar' => 'Calendar',
        'close_appointments' => 'Close Appointments',
        'users' => 'Users',
        'categories' => 'Categories',
        'locations' => 'Locations',
        'audit' => 'Audit',
        'documents' => 'Documents',
        'configuration' => 'Configuration',
        'my_profile' => 'My Profile',
        'logout' => 'Logout',

        // Login Page (sesion_iniciar.php)
        'login_title' => 'Login',
        'login_user' => 'Username',
        'login_password' => 'Password',
        'login_button' => 'Sign In',
        'login_forgot_password' => 'I forgot my user password',
        'login_error_inactive' => 'Your user account has been disabled.',
        'login_error_password' => 'Incorrect password.',
        'login_error_not_found' => 'User not found.',
        'login_error_session_expired' => 'Your session has expired due to inactivity. Please log in again.',
        'login_back_to_home' => 'Back to home',

        // Dashboard
        'dashboard_welcome_to' => 'Welcome to',
        'dashboard_subtitle' => 'Your personal assistant for appointment management.',
        'dashboard_card_schedule' => 'Schedule Appointment',
        'dashboard_card_calendar' => 'View Calendar',
        'dashboard_card_clients' => 'Manage Clients',

        // Clients Page (clientes_lista.php)
        'clients_title' => 'Client Management',
        'clients_register_new' => 'Register New Client',
        'clients_form_name' => 'Full Name',
        'clients_form_phone' => 'Phone Number',
        'clients_form_email' => 'Email Address',
        'clients_form_save' => 'Save Client',
        'clients_list_title' => 'Client List',
        'clients_list_for' => 'For',
        'clients_col_name' => 'Name',
        'clients_col_phone' => 'Phone',
        'clients_col_email' => 'Email',
        'clients_col_status' => 'Status',
        'clients_form_address1' => 'Address 1',
        'clients_form_address2' => 'Address 2 (Optional)',
        'clients_form_country' => 'Country',
        'clients_form_state' => 'State / Province',
        'clients_form_city' => 'City',
        'clients_form_zip' => 'Zip Code',
        'clients_form_notes' => 'Additional Notes',
        'clients_form_communication' => 'Communication Preferences:',
        'clients_form_sms_notifications' => 'Receive SMS notifications',
        'clients_form_email_notifications' => 'Receive Email notifications',
        'clients_form_clear' => 'Clear Form',
        'clients_no_clients' => 'No clients registered yet.',
        'clients_confirm_deactivate' => 'Are you sure you want to deactivate this client? It cannot be used for new appointments, but its history will be preserved.',
        'clients_edit_title' => 'Edit Client',
        'clients_editing' => 'Editing',
        'clients_form_active' => 'Client Active',
        'clients_form_update' => 'Update Client',

        // Businesses Page (negocios_configuracion.php)
        'businesses_title' => 'Business Configuration',
        'businesses_manage_title' => 'Business Management',
        'businesses_select_or_create' => 'Select a business to edit or create a new one.',
        'businesses_status_suspended' => 'Suspended',
        'businesses_status_deleted' => 'Deleted',
        'businesses_create_new' => 'Create New Business',
        'businesses_config_for' => 'Configuration for',
        'businesses_form_id' => 'Business ID',
        'businesses_form_name' => 'Business Name',
        'businesses_form_phone' => 'Phone',
        'businesses_form_phone_local' => 'Local number',
        'businesses_form_email' => 'Contact Email',
        'businesses_form_category' => 'Business Category',
        'businesses_form_no_category' => '-- No Category --',
        'businesses_form_status' => 'Business Status',
        'businesses_form_address1' => 'Address 1',
        'businesses_form_address2' => 'Address 2 (Optional)',
        'businesses_form_country' => 'Country',
        'businesses_form_select_country' => 'Select a country...',
        'businesses_form_state' => 'State / Province',
        'businesses_form_loading' => 'Loading...',
        'businesses_form_city' => 'City',
        'businesses_form_zip' => 'Zip Code',
        'businesses_schedule_title' => 'Work Schedule',
        'businesses_schedule_days' => 'Work Days',
        'day_1' => 'Monday', 'day_2' => 'Tuesday', 'day_3' => 'Wednesday', 'day_4' => 'Thursday', 'day_5' => 'Friday', 'day_6' => 'Saturday', 'day_7' => 'Sunday',
        'businesses_schedule_start' => 'Start Time',
        'businesses_schedule_end' => 'End Time',
        'businesses_schedule_interval' => 'Interval (minutes)',
        'businesses_trial_title' => 'Trial Period Management',
        'businesses_trial_reg_date' => 'Registration Date',
        'businesses_trial_start_date' => 'Enablement Date (Trial Start)',
        'businesses_trial_days' => 'Assigned Trial Days',
        'businesses_trial_end_date' => 'Deactivation Date (Manual)',
        'businesses_trial_note' => 'Adjust the days or the end date. The end date has priority.',
        'businesses_bg_image_title' => 'Background Image',
        'businesses_bg_image_upload' => 'Upload new background image (optional)',
        'businesses_bg_image_current' => 'Current Image:',
        'businesses_form_save' => 'Save Configuration',
        'businesses_create_title' => 'Create New Business',
        'businesses_create_instructions' => 'Complete the basic details. You can add more details (schedules, image, etc.) after creating it.',
        'businesses_create_owner_title' => 'Create Owner User',
        'businesses_create_owner_instructions' => 'An \'Owner\' user will be created for this new business.',
        'businesses_create_owner_user' => 'Owner Username',
        'businesses_create_owner_password' => 'Password for Owner',
        'businesses_create_owner_email' => 'Owner User\'s Email',
        'businesses_create_button' => 'Create Business and Owner User',

        // Services Page (servicios_lista.php & servicios_editar.php)
        'services_title' => 'Service Management',
        'services_register_new' => 'Register New Service',
        'services_form_name' => 'Service Name',
        'services_form_duration' => 'Duration',
        'duration_minutes' => 'Minutes',
        'duration_hours' => 'Hours',
        'duration_days' => 'Days',
        'services_form_price' => 'Price (optional)',
        'services_form_save' => 'Save Service',
        'services_form_clear' => 'Clear Form',
        'services_list_title' => 'Service List',
        'services_col_service' => 'Service',
        'services_col_duration' => 'Duration',
        'services_col_price' => 'Price',
        'services_confirm_deactivate' => 'Are you sure you want to deactivate this service?',
        'services_no_services' => 'No services registered yet.',
        'services_edit_title' => 'Edit Service',
        'services_editing' => 'Editing Service',
        'services_form_active' => 'Service Active',
        'services_form_update' => 'Update Service',

        // Appointments Page (citas_lista.php & citas_editar.php)
        'appointments_title' => 'Appointment Management',
        'appointments_schedule_new' => 'Schedule New Appointment',
        'appointments_type' => 'Appointment Type',
        'appointments_type_service' => 'Service Appointment',
        'appointments_type_meeting' => 'Meeting',
        'appointments_client' => 'Client',
        'appointments_select_client' => 'Select a client...',
        'appointments_service' => 'Service',
        'appointments_select_service' => 'Select a service...',
        'appointments_date' => 'Appointment Date',
        'appointments_time' => 'Appointment Time',
        'appointments_select_time' => 'Select a time...',
        'appointments_additional_desc' => 'Additional Description',
        'appointments_meeting_subject' => 'Meeting Subject',
        'appointments_meeting_guests' => 'Meeting Guests',
        'appointments_add_guest' => '+ Add Guest',
        'appointments_schedule_button' => 'Schedule Appointment',
        'appointments_list_title' => 'Appointment List',
        'appointments_filter_day' => 'Day:',
        'appointments_filter_button' => 'Filter',
        'appointments_prev_day' => '⬅️ Previous',
        'appointments_next_day' => 'Next ➡️',
        'appointments_col_schedule' => 'Schedule',
        'appointments_col_duration' => 'Duration',
        'appointments_no_appointments_for_day' => 'No appointments scheduled for',
        'appointments_edit_title' => 'Edit Appointment',
        'appointments_editing_title' => 'Editing Appointment',

        // Calendar Page (calendario_ver.php)
        'calendar_title' => 'Appointment Calendar',

        // Close Appointments Page (citas_cerrar_vencidas.php)
        'close_appointments_title' => 'Close Overdue Appointments',
        'close_appointments_header' => 'Manual Closing of Overdue Appointments',
        'close_appointments_desc_1' => "This tool will find all appointments with 'Pending' status whose date and time have already passed and will automatically update them to 'Overdue' status.",
        'close_appointments_desc_2' => 'This helps keep your schedule clean and your reports up to date.',
        'close_appointments_button' => 'Start Closing Process',
        'close_appointments_success' => "Process completed. {count} appointments have been updated to 'Overdue' status.",

        // Users Page (usuarios_lista.php & usuarios_editar.php)
        'users_title' => 'User Management',
        'users_register_new' => 'Register New User',
        'users_form_username' => 'Username',
        'users_form_email' => 'Email Address',
        'users_form_password' => 'Password',
        'users_form_role' => 'Role',
        'users_role_owner' => 'Owner',
        'users_form_business' => 'Assigned Business',
        'users_form_active' => 'User Active',
        'users_form_save' => 'Save User',
        'users_list_title' => 'User List',
        'users_col_user' => 'User',
        'users_col_business' => 'Business',
        'users_confirm_delete' => 'Are you sure you want to delete this user?',
        'users_not_allowed' => '(Not allowed)',
        'users_no_users' => 'No users registered.',
        'users_edit_title' => 'Edit User',
        'users_editing' => 'Editing',
        'users_form_new_password' => 'New Password',
        'users_form_new_password_placeholder' => 'Leave blank to keep current',
        'users_form_update' => 'Update User',

        // Categories Page (categorias_lista.php, etc.)
        'categories_title' => 'Category Management',
        'categories_create_new' => 'Create New Category',
        'categories_list_title' => 'Business Category Management',
        'categories_col_name' => 'Category Name',
        'categories_col_desc' => 'Description',
        'categories_confirm_delete' => 'Are you sure you want to delete this category? It might be in use by a business.',
        'categories_edit_title' => 'Edit Category',
        'categories_editing' => 'Editing Category',
        'categories_form_active' => 'Category Active',
        'categories_form_update' => 'Update Category',

        // Locations Page (paises_lista.php, estados_lista.php, etc.)
        'locations_countries_title' => 'Country Management',
        'locations_register_country' => 'Register New Country',
        'locations_form_country_name' => 'Country Name',
        'locations_form_country_code' => 'Code (2 letters, e.g., US)',
        'locations_form_phone_code' => 'Phone Code (e.g., +1)',
        'locations_form_timezone' => 'Main Timezone',
        'locations_form_select_timezone' => 'Select...',
        'locations_form_save_country' => 'Save Country',
        'locations_list_countries' => 'Country List',
        'locations_col_country' => 'Country',
        'locations_col_code' => 'Code',
        'locations_col_phone' => 'Phone',
        'locations_col_timezone' => 'Timezone',
        'locations_action_states' => 'States',
        'locations_confirm_delete_country' => 'Are you sure you want to delete this country and ALL its associated states?',
        'locations_no_countries' => 'No countries registered.',
        'locations_edit_country_title' => 'Edit Country',
        'locations_editing_country' => 'Editing Country',
        'locations_update_country' => 'Update Country',
        'locations_states_title' => 'State Management for {country}',
        'locations_back_to_countries' => '← Back to Countries',
        'locations_register_state' => 'Register New State',
        'locations_form_state_name' => 'State / Province Name',
        'locations_form_save_state' => 'Save State',
        'locations_list_states' => 'State List',
        'locations_confirm_delete_state' => 'Are you sure?',
        'locations_no_states' => 'No states registered for this country.',
        'locations_edit_state_title' => 'Edit State',
        'locations_editing_state' => 'Editing State',
        'locations_update_state' => 'Update State',

        // Audit Page (auditoria_reporte.php)
        'audit_title' => 'Audit Report',
        'audit_filter_title' => 'Filter Records',
        'audit_filter_from' => 'From',
        'audit_filter_to' => 'To',
        'audit_filter_all' => 'All',
        'audit_filter_clear' => 'Clear',
        'audit_report_title' => 'Audit Report (Audit Trail)',
        'audit_showing_records' => 'Showing {count} of {total} Records',
        'audit_col_datetime' => 'Date & Time',
        'audit_col_ip' => 'IP Address',
        'audit_user_system' => 'System/Deleted',
        'audit_business_na' => 'N/A',
        'audit_no_records' => 'No audit records match the filters.',

        // Documents Page (seleccionar_resumen.php, etc.)
        'documents_title' => 'Documents',
        'documents_select_or_upload' => 'Select a document to view, edit, or send, or upload a new one.',
        'documents_no_files' => 'No documents found in the directory.',
        'documents_view' => 'View',
        'documents_send' => 'Send',
        'documents_confirm_send' => 'Are you sure you want to email this document?',
        'documents_confirm_delete' => 'Are you sure you want to permanently delete this document?',
        'documents_upload_title' => 'Upload New Document',
        'documents_upload_select' => 'Select file (.txt, .pdf, .md)',
        'documents_upload_button' => 'Upload Document',
        'documents_edit_md_title' => 'Edit Markdown Document',
        'documents_editing' => 'Editing',
        'documents_edit_txt_title' => 'Edit Document',
        'documents_edit_txt_note' => 'Note: Headers (FROM, TO, SUBJECT) are not editable from here.',
        'documents_send_pdf_title' => 'Send PDF Document',
        'documents_send_pdf_about_to_send' => 'You are about to send the following document as an attachment:',
        'documents_send_pdf_file' => 'File',
        'documents_send_pdf_to' => 'Recipient\'s Email (TO):',
        'documents_send_pdf_subject' => 'Email Subject:',
        'documents_send_pdf_button' => 'Send Email with Attachment',
        'documents_viewer_title' => 'Viewer',

        // Email Content
        'email_hello' => 'Hello {name}!',
        'email_regards' => 'Regards,',
        'email_team' => 'The ZApp Citas Team',
        'email_service' => 'Service',
        'email_meeting_subject' => 'Subject',
        'email_date' => 'Date',
        'email_time' => 'Time',
        'email_client_data' => 'Client Details',
        'email_name' => 'Name',
        'email_email' => 'Email',
        'email_phone' => 'Phone',
        'email_not_specified' => 'Not specified',

        // New Appointment
        'email_new_subject_service' => 'Your appointment at {business_name} is confirmed',
        'email_new_subject_meeting' => 'Meeting Invitation: {event_title}',
        'email_new_title_service' => 'Your appointment has been successfully scheduled!',
        'email_new_title_meeting' => 'You have been invited to a meeting!',
        'email_new_body' => 'Here are the details:',
        'email_new_footer' => '<strong>Important:</strong> Please arrive 5 minutes before the agreed time to respect the schedule of other clients.',

        // Modified Appointment
        'email_modified_subject_service' => 'Update on your appointment at {business_name}',
        'email_modified_subject_meeting' => 'Meeting Update: {event_title}',
        'email_modified_title_service' => 'Your appointment has been modified!',
        'email_modified_title_meeting' => 'The meeting has been modified',
        'email_modified_body' => 'These are the new details:',
        'email_modified_footer' => 'Please review the new details and contact us if you have any questions.',

        // Cancelled Appointment
        'email_cancelled_subject_service' => 'Cancellation of your appointment at {business_name}',
        'email_cancelled_subject_meeting' => 'Meeting Cancellation: {event_title}',
        'email_cancelled_title_service' => 'Your appointment has been cancelled.',
        'email_cancelled_title_meeting' => 'The meeting has been cancelled',
        'email_cancelled_body' => 'We regret to inform you that the following event has been cancelled:',
        'email_cancelled_footer' => 'If you wish to reschedule, please do not hesitate to contact us.',

        // Password Recovery
        'email_recovery_subject' => 'Password Recovery - ZApp Citas',
        'email_recovery_title' => 'Password Recovery',
        'email_recovery_body' => 'You have requested to reset your password. Here are your new login details:',
        'email_recovery_user' => 'Username',
        'email_recovery_password' => 'New Temporary Password',
        'email_recovery_footer' => 'We recommend logging in and changing this password to one of your choice as soon as possible.',
        'email_recovery_ignore' => 'If you did not request this, you can ignore this email.',
        'email_recovery_generic_success' => 'If your email is in our system, you will receive an email with instructions.',

        // Forgot Password Page
        'forgot_password_title' => 'Recover Password',
        'forgot_password_instructions' => 'Enter your email address and we will send you a new temporary password if the account exists.',
        'forgot_password_button' => 'Send Instructions',
        'forgot_password_back_to_login' => 'Back to Login',
    ]
];

// 3. Función helper para obtener traducciones
function __($key) {
    global $lang, $translations;
    return $translations[$lang][$key] ?? $key;
}

?>